const express = require('express');
const fs = require('fs');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.get('/', (req,res)=>{res.send(`<body style="background:#000;color:#fff;font-family:Arial;padding:15px;text-align:center"><h1 style="color:red">REMIX22 ADMIN</h1><input id="titulo" placeholder="Nombre" style="width:90%;padding:12px;margin:6px;background:#222;color:#fff;border:none;border-radius:8px"><input id="imagen" placeholder="Link imagen https://..." style="width:90%;padding:12px;margin:6px;background:#222;color:#fff;border:none;border-radius:8px"><input id="link" placeholder="Link YouTube o Drive" style="width:90%;padding:12px;margin:6px;background:#222;color:#fff;border:none;border-radius:8px"><button onclick="agregar()" style="width:92%;padding:12px;background:#b30000;color:#fff;border:none;border-radius:8px;font-weight:bold">+ AGREGAR</button><button onclick="guardar()" style="width:92%;padding:12px;margin-top:8px;background:#00aa00;color:#fff;border:none;border-radius:8px">GUARDAR CAMBIOS</button><div id="lista"></div><p><a href="/ver" style="color:#0f0">Ver app /ver</a> | <a href="/apk" style="color:yellow">COMO HACER APK</a></p><script>const API='/pelis';let pelis=[];async function cargar(){const r=await fetch(API);pelis=await r.json();mostrar();}function mostrar(){const c=document.getElementById('lista');c.innerHTML='';pelis.forEach((p,i)=>{c.innerHTML+='<div style="background:#111;padding:10px;margin:10px;border-radius:10px;display:flex;gap:10px"><img src="'+p.imagen+'" style="width:60px;height:80px;object-fit:cover" onerror="this.src=\'https://via.placeholder.com/60x80?text=No+Img\'"><div><b>'+p.titulo+'</b><br><a href="#" onclick="borrar('+i+')" style="color:red">Borrar</a></div></div>'})}function agregar(){const t=titulo.value,im=imagen.value,li=link.value;if(!t||!im||!li){alert('Completa los 3');return}pelis.push({titulo:t,imagen:im,link:li});titulo.value='';imagen.value='';link.value='';mostrar();}async function guardar(){await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pelis)});alert('Guardado OK - anda a /ver');}function borrar(i){pelis.splice(i,1);mostrar();}cargar();<\/script></body>`)});

app.get('/ver', (req,res)=>{res.send(`<body style="background:#000;color:#fff;font-family:Arial;margin:0"><div style="background:#b30000;padding:15px;text-align:center;font-weight:bold;position:sticky;top:0;z-index:10">REMIX22 - TOCA VER</div><div id="lista" style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:10px">Cargando...</div><div id="player" style="display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:#000;z-index:100;padding:10px;box-sizing:border-box"><div style="display:flex;justify-content:space-between"><b id="ptitulo"></b><button onclick="cerrar()" style="background:red;color:#fff;border:none;padding:8px 15px;border-radius:5px">X CERRAR</button></div><div id="pvideo" style="margin-top:10px;width:100%;height:80vh;background:#111"></div></div><script>function getEmbed(url){if(url.includes('youtube.com')||url.includes('youtu.be')){let id='';if(url.includes('v=')){id=url.split('v=')[1].split('&')[0]}else if(url.includes('youtu.be/')){id=url.split('youtu.be/')[1].split('?')[0]} return '<iframe width="100%" height="100%" src="https://www.youtube.com/embed/'+id+'" frameborder="0" allowfullscreen></iframe>'}else if(url.includes('drive.google.com')){let id=url.match(/\\/d\\/([^\\/]+)/);if(id) return '<iframe src="https://drive.google.com/file/d/'+id[1]+'/preview" width="100%" height="100%" allow="autoplay"></iframe>'; return '<iframe src="'+url+'" width="100%" height="100%"></iframe>'}else{return '<iframe src="'+url+'" width="100%" height="100%" frameborder="0" allowfullscreen></iframe>'}}function verPeli(titulo,link){document.getElementById('ptitulo').innerText=titulo;document.getElementById('pvideo').innerHTML=getEmbed(link);document.getElementById('player').style.display='block';}function cerrar(){document.getElementById('player').style.display='none';document.getElementById('pvideo').innerHTML='';}async function cargar(){const r=await fetch('/pelis');const pelis=await r.json();const c=document.getElementById('lista');if(!pelis.length){c.innerHTML='Sin pelis - agrega en el admin';return}c.innerHTML='';pelis.forEach(p=>{c.innerHTML+='<div style="background:#111;border-radius:12px;overflow:hidden"><img src="'+p.imagen+'" style="width:100%;height:220px;object-fit:cover" onerror="this.src=\\'https://via.placeholder.com/300x220?text=Sin+Imagen\\'"><div style="padding:8px;text-align:center;height:35px">'+p.titulo+'</div><button onclick="verPeli(\\''+p.titulo.replace(/'/g,'')+'\\',\\''+p.link+'\\')" style="display:block;width:92%;background:#b30000;color:#fff;text-align:center;padding:10px;margin:8px;border:none;border-radius:8px;font-weight:bold">▶ VER AHORA</button></div>'})}cargar();<\/script></body>`)});

app.get('/apk', (req,res)=>{res.send(`<body style="background:#000;color:#fff;font-family:Arial;padding:20px;text-align:center"><h1 style="color:red">COMO HACER TU APK</h1><p>Tu pagina /ver YA ES LA APP. Para tener el .apk hace esto:</p><div style="text-align:left;background:#111;padding:15px;border-radius:10px"><p><b>Paso 1:</b> Anda a <a href="https://appsgeyser.com" target="_blank" style="color:yellow">appsgeyser.com</a></p><p><b>Paso 2:</b> Elegi "Website"</p><p><b>Paso 3:</b> Pega este link: <br><code style="background:#222;padding:5px">https://remix22.onrender.com/ver</code></p><p><b>Paso 4:</b> Pone nombre REMIX22, subi logo y dale a CREATE</p><p><b>Paso 5:</b> Te baja el APK listo para instalar</p></div><p style="margin-top:20px">O mas facil en Android: abre /ver en Chrome > menu (3 puntitos) > Agregar a pantalla principal > ya queda como APP</p><a href="/ver" style="display:block;background:#b30000;color:#fff;padding:15px;border-radius:10px;text-decoration:none;margin-top:20px">VOLVER A LA APP</a></body>`)});

app.get('/pelis', (req,res)=>{try{res.send(fs.readFileSync('./pelis.json','utf8'))}catch{res.send('[]')}});
app.post('/pelis', (req,res)=>{fs.writeFileSync('./pelis.json', JSON.stringify(req.body, null, 2));res.send({ok:true})});
app.listen(PORT, ()=>console.log('ok'));
